# Site settings
title: Bill Capecchi
description: 'Sr. Simulation and Modeling Engineer<br>Based in Minneapolis, MN' #PhD Physicist - Climber, Hiker, Marathoner - Space Travel Enthusiast<br>
#url: 'http://capecchi.github.io'
url: 'http://www.williamcapecchi.com'
baseurl: ''
# baseurl: '/jekyll-uno/' #old
google_analytics: 'UA-101721150-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bill Capecchi'
  email: william.capecchi@gmail.com
  #twitter_username:
  facebook_username: bill.capecchi
  github_username:  capecchi
  linkedin_username:  william-capecchi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate'] #,'jekyll-sitemap']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
