# Site settings
title: Bill Capecchi
description: 'PhD Physicist and Data Scientist'
url: 'http://capecchi.github.io'
baseurl: './'
# baseurl: '/jekyll-uno/' #old
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bill Capecchi'
  email: william.capecchi@gmail.com
  #twitter_username: 
  facebook_username: bill.capecchi
  github_username:  capecchi
  linkedin_username:  william-capecchi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
